use_default_settings:
  engines:
    keep_only:
      - bing
      - brave
      - mojeek
      - startpage

general:
  instance_name: "Quill search"

search:
  safe_search: 1
  default_lang: en
  ban_time_on_fail: 1
  max_ban_time_on_fail: 30
  formats:
    - html
    - json

server:
  secret_key: "ultrasecretkey"
  limiter: true
  image_proxy: false

engines:
  - name: bing
    disabled: false
  - name: mojeek
    disabled: false
  - name: startpage
    disabled: false
  - name: brave
    disabled: false
